# title: 'Motivational Site' # optionally override title
locale: 'en'
date_format: '%Y.%m.%d.' # for strftime() calls

workout:
  sheet_id:  "" # from google spreadsheet URL (part between https://docs.google.com/spreadsheets/d/ and /edit#gid=...)
  sheet_range:  "A2:B"
  date_format: "%Y.%m.%d."

redmine:
  url: 'https://example.com/'
  api_key: '' # enable REST API and copy key from user account page
  contributions_and_timeline: true  # enable contributions calendar and open/closed timeline
  in_progress_id: 2 # issue_status id for 'In Progress'
  closed_id: 2 # issue_status id for 'Closed'
  issue_state_colors:
    1: '#839fd4ad'
    2: '#ffbf00c2'
    5: '#00ce25ad'
    6: '#00901aad'

journaling:
  dav:
    hostname: 'example.com'
    protocol: 'https'
    baseurl: 'remote.php/dav/files/username/'  # e.g. for NextCloud share
    login: 'username'
    password: 'password'
    path: 'location-of-my-journal.md'
  day_prefix: '### '
  date_format: '%Y.%m.%d.'
